version: "3.5"

networks:
  default:
    name: example.com

services:
  master:
    image: '${HADOOP_TESTING_IMAGE}'
    user: root
    command: supervisord -c /etc/master.supervisord.conf
    container_name: master
    hostname: master
    domainname: example.com
    ports:
      - 8020:8020    # NN
      - 9000:9000    # NN
      - 50070:50070  # NN webui
      - 8088:8088    # RM webui
      - 88:88/udp    # Kerberos
      - 749:749      # Kerberos
    tmpfs:
      - /tmp:noexec

  worker:
    image: '${HADOOP_TESTING_IMAGE}'
    user: root
    command: supervisord -c /etc/worker.supervisord.conf
    container_name: worker
    hostname: worker
    domainname: example.com
    ports:
      - 50075:50075  # DN webui
      - 8042:8042    # NM webui
    tmpfs:
      - /tmp:noexec

  edge:
    image: '${HADOOP_TESTING_IMAGE}'
    user: root
    command: supervisord -c /etc/edge.supervisord.conf
    container_name: edge
    hostname: edge
    domainname: example.com
